import numpy as np
import pywt

def generate_verilog_coeffs(coef_width, coef_frac, file_path="D:/project/zu9_modifield+pulse_iir/PL/FMC_FH8052_zu9/FMC_FH8052.srcs/sources_1/imports/src/simulation/coef_params.vh"):
    """
    生成小波系数并写入为 Verilog 参数定义文件 (.vh)
    
    Args:
        coef_width: 总位宽 (例如 25)
        coef_frac: 小数位宽 (例如 23)
        file_path: 输出文件路径
    """
    
    # 1. 获取 sym4 系数 (pywt 库)
    wavelet = pywt.Wavelet('sym4')
    h_dec_float = wavelet.dec_lo  # 分解低通滤波器系数
    # h_rec 在硬件实现中通常是 h_dec 的逆序 (根据你之前的代码逻辑)
    h_rec_float = h_dec_float[::-1] 

    scale_factor = 1 << coef_frac
    mask = (1 << coef_width) - 1

    print(f"Generating Verilog parameters: Width={coef_width}, Frac={coef_frac}")

    with open(file_path, 'w') as f:
        f.write(f"// Auto-generated by Python script\n")
        f.write(f"// Width: {coef_width}, Frac: {coef_frac}\n")
        f.write(f"// Scale Factor: {scale_factor}\n\n")

        # -------------------------------------------------
        # 写入分解系数 (DEC_H)
        # -------------------------------------------------
        f.write("// Decomposition Coefficients\n")
        for i, val in enumerate(h_dec_float):
            # 量化
            int_val = int(round(val * scale_factor))
            # 补码处理 (为了生成正确的 hex)
            twos_comp = int_val & mask
            
            # 生成 Verilog 语句: parameter DEC_H0 = 25'sh<HEX>;
            # 'sh 表示有符号十六进制，更紧凑
            hex_str = f"{twos_comp:x}"
            line = f"parameter DEC_H{i} = {coef_width}'sh{hex_str}; // Float: {val:.6f}\n"
            f.write(line)

        f.write("\n")

        # -------------------------------------------------
        # 写入重构系数 (REC_H) - 按照你的逆序逻辑
        # -------------------------------------------------
        f.write("// Reconstruction Coefficients (Reverse of DEC)\n")
        # 你的逻辑是 REC_H0 = DEC_H7, REC_H1 = DEC_H6...
        # 这里我们直接定义数值，或者引用 DEC_H 参数都可以。
        # 为了保险起见，我们直接引用上面定义好的 DEC_H 参数，这样文件更小
        for i in range(len(h_dec_float)):
            target_dec_idx = len(h_dec_float) - 1 - i
            line = f"parameter REC_H{i} = DEC_H{target_dec_idx};\n"
            f.write(line)

    print(f"-> Successfully written to {file_path}")

# ==========================================
# 主程序调用
# ==========================================
if __name__ == "__main__":
    # 只需要在这里修改位宽，然后运行脚本即可
    generate_verilog_coeffs(coef_width=18, coef_frac=16)